### ISSUE TITLE
domain name has been squatted

### ISSUE THREAD

**Issue by glyph** [colingourlay/name-that-blue#34]
namethatblue . com now points to a site which directs me to "Mac cleaning" malware.

possibly change the link in the repo description, and ... maybe put it up on a github pages site instead?

(I loved this thing as a gag to show people...)

**Comment by colingourlay** [comment]
@glyph this may be the most belated issue reply on github dot com, but I wanted to let you know I appreciate you looking out for me! I've just re-deployed it to Netlify (funny how people go looking for these silly little games again, off the back of Wordle's popularity). Enjoy! https://namethatblue.netlify.app/

**Comment by glyph** [comment]
Thank you @colingourlay !
